# -*- coding: utf-8 -*-
{
    'name': 'D4E Swiss-Creative 2 Website',
    'version': '14.0.0.1',
    'category': 'Inventory',
    'summary': '',
    'description': "",
    'website': 'https://d4e-ch.odoo.com',
    'depends': [
        'product',
        'website_sale',
        'stock',
        'sale_stock',
        'website_sale_stock',
        # 'purchase',
        # 'sale_management',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/uom_data.xml',
        'data/website_frs_menu.xml',
        'data/mail_template.xml',
        'views/product_views.xml',
        # 'views/sale_views.xml',
        'wizard/supplier_invoice_sale_generator.xml',
        'report/recap_supp_invoice.xml',
        'report/supp_invoice_recap_template.xml',
        'views/templates.xml',
        'views/res_partner_views.xml',
        'views/sale_recap_mail_views.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
